// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package com.example.tutorial.protos;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test_proto.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 Id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>int64 contactNumber = 4;</code>
   * @return The contactNumber.
   */
  long getContactNumber();
}
