// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

package com.example.tutorial.protos;

public interface UsersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test_proto.Users)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .test_proto.User users = 1;</code>
   */
  java.util.List<com.example.tutorial.protos.User> 
      getUsersList();
  /**
   * <code>repeated .test_proto.User users = 1;</code>
   */
  com.example.tutorial.protos.User getUsers(int index);
  /**
   * <code>repeated .test_proto.User users = 1;</code>
   */
  int getUsersCount();
  /**
   * <code>repeated .test_proto.User users = 1;</code>
   */
  java.util.List<? extends com.example.tutorial.protos.UserOrBuilder> 
      getUsersOrBuilderList();
  /**
   * <code>repeated .test_proto.User users = 1;</code>
   */
  com.example.tutorial.protos.UserOrBuilder getUsersOrBuilder(
      int index);
}
